name: Check Links
on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Ruby
      - name: Install Ruby
        run: sudo apt-get install ruby-full -y

      # Install awesome_bot
      - name: Install awesome_bot
        run: gem install awesome_bot

      # Run awesome_bot on README.md
      - name: Run awesome_bot
        run: awesome_bot README.md --allow-redirect
