name: Check README Links

on:
  push:
    branches: [ main, master ]
    paths:
      - 'README.md'
      - '.github/workflows/awesome-bot.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'README.md'
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  awesome_bot:
    runs-on: ubuntu-latest
    name: Check links in README
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false
          
      - name: Install awesome_bot
        run: gem install awesome_bot
        
      - name: Run awesome_bot on README
        run: |
          awesome_bot README.md \
            --allow-dupe \
            --allow-redirect \
            --request-delay 1 \
            --set-timeout 30 \
            --skip-save-results
        continue-on-error: false
        
      - name: Comment on PR (if PR and links are broken)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Some links in the README appear to be broken. Please check the workflow logs for details.'
            })
            
      - name: Upload results (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: awesome-bot-results
          path: ab-results-*.json
          retention-days: 30
